### PR TITLE
[WIP New Feature] IoT Dashboard for Agricultural Sensors

### PR DESCRIPTION
**Pull request by bepitulaz**
Do you fancy monitoring your real time farm condition? We do. Hence, we, at Tanibox, are deciding to start to develop a new feature to support any DIY sensors in Tania. Our plan is using MQTT for the communication protocol between the devices and Tania. So, everybody can connect their Raspberry Pi, ESP8266, Arduino, or any dev board to Tania easier.

Any feedbacks or comments are welcome :) Don't forget we also have an issue tracker in https://gettania.atlassian.net.

The preview of the new dashboard.
Preview

### CODE REVIEW

**Comment by bepitulaz** [comment]
The preview of the latest commit:

**The device manager**
index

**The resource manager**
Resources manager

**Comment by lynxluna** [comment]
This is nice progress. What is the protocol you're using? MQTT?

**Comment by bepitulaz** [comment]
@lynxluna yes, I'm using MQTT because it is the widely used protocol for IoT.

**Comment by bepitulaz** [comment]
The last commit for this feature has been pushed. Now, DIY sensors can be attached to Tania as long as the user installs their MQTT broker. Then, the user can put the host and the port information into Tania's preferences. Here is the screenshot.

Tania's Preferences

This is the detail information of the device. The MQTT topics to subscribe and publish are also listed. The topics are actually the Resource ID of the device.

Device Information

**Comment by bepitulaz** [comment]
I think we can merge this IoT dashboard feature to the development branch.

**Pull request merged**
