### PR TITLE
Dockerising

### PR DESCRIPTION
**Pull request by lynxluna**
The first step to dockerise to fulfil #23 

- [x] Rearrange the project files
- [x] Done setting up Dockerfiles
- [x] Done setting up docker-compose

### CODE REVIEW

**Comment by bepitulaz** [comment]
I'll install docker on my machine, then review this PR. Thanks.

**Comment by ucay** [comment]
If the application moved to `/tania` , i think repository, translation, and web should be moved too.

**Comment by lynxluna** [comment]
This build is still not running properly. Anyone who can debug the problem, I'll be very thankful. It's my lack experience using PHP mostly.

So to try, it's already `compose`-able.

`docker-compose up -d`

And the setup and migration will run.

But when you access it using `/localhost`, it gives you error on permission denied.

**Comment by lynxluna** [comment]
Looks like I'm able to make it work. But because the db will start a little bit longer, it's advisable to manually setup the `services`

```
docker-compose up -d db
```

Wait for 10-30 seconds

```
docker-compose up -d
```

**Comment by mathewpeterson** [comment]
Hello,

I've been watching this this repo since it hit HN because I'm interested in open source applications using Symfony. 

I also have experience using Docker so this PR got my attention.

- Not sure why the app is being moved but I don't think that's necessary. 
- Entries in `.gitignore` should be in someones global `.gitignore` and not the projects `.gitignore`
- xdebug should not be installed in main docker file
- you should only need a single `nginx.conf` since the docker container would only be used for this app
- We can get away from using the `parameters.yml` file and move to using environment variables - which favors 12factor 
- This commit has a bunch of files that should have not been committed:
  - vendor
  - cache

In effect, I don't think this PR should move forward since it has a lot of un necessary stuff.

If you would like, I am happy to help in any that I can.

**Comment by lynxluna** [comment]
Hey @mathewpeterson, thanks for the input. I just mishmashed and try `Dockerfiles` scattered on the net, hence the messiness.

- There's no reason except for my own convenience. I am used to create docker with this pattern so the app will be isolated with other files, e.g. `scripts` `conf` et. al.
- Yes, noted, I was messed up
- The first time I thought it is for development, but then I think I change my goal to be able to run it on prod
- Yes, I created new branch for cleaning up after knowing how to make it work.
- This what I have discussed with @bepitulaz when I try to dockerise this repo.
- Yes noted.

I agree not to move this PR forward. I worked on new one and take your suggestion. It's still unfinished but has been on my private fork on `feature/docker-single` branch.

**Comment by bepitulaz** [comment]
Hi @lynxluna @mathewpeterson,

My knowledge in containerize application with Docker is pretty limited. I agree if you guys think this PR is better to move forward later.

@mathewpeterson how to replace `parameters.yml` with environment variables? What should I change in the Symfony side?

Thanks.

**Comment by mathewpeterson** [comment]
@bepitulaz There is a [blog post](https://symfony.com/blog/new-in-symfony-3-2-runtime-environment-variables) on the Symfony Blog.  I can help once we get the container stuff working properly.

@lynxluna Would you like to close this PR and open a new one from your fork as `WIP`? I can help you from there.

In the mean time, I will also work on a separate approach to containerizing this app but please do not feel like you need to accept it.

**Comment by lynxluna** [comment]
Ayup, I need to cleanup a bit and will create new PR

**Pull request closed without merging**
