### PR TITLE
Add bower support and datetimepicker in task due date

### PR DESCRIPTION
**Pull request by farizyoga**
@bepitulaz, please review my PR

thanks

### CODE REVIEW

**Comment by farizyoga** [comment]
@bepitulaz, please review my PR

**Comment by bepitulaz** [comment]
Hi @farizyoga,

I'll review it today. Thanks btw.

**Comment by bepitulaz** [comment]
Hi @farizyoga, your PR has been merged to `development` branch. Can you help me to implement it in `/plants/create` page? The seedling date field. Please, propose your PR to the `development` branch.

Thanks :)

**Comment by farizyoga** [comment]
oke thanks @bepitulaz, i will do it letter

**Pull request closed without merging**
